apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
            - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretRef:
                name: my-secret
                key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                name: my-secret
                key: MYSQL_DATABASE

        volumeMounts:
        - name: data-mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: data-mysql
        persistentVolumeClaim:
          claimName: data-mysql
---
appVersion: v1
kind: Service
metadata:
  name: connection-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None