stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  service:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t eduardosdl/app-php:1.0 app/.
    - docker push eduardosdl/app-php:1.0 app/.

deploy_gcp:
  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY
  
  script:
     - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./pipeline/ && sudo git clone https://gitlab.com/.../pipeline.git && cd pipeline && sudo chmod +x ./up.sh && ./up.sh"