apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql
spec:
  acessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: eduardosdl/mysql-php:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data-mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: data-mysql
        persistentVolumeClaim:
          claimName: data-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec: 
      containers:
      - name: php
        image: eduardosdl/backend-php:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80